### ISSUE TITLE
Using PatchedTreeModel changes Gtk.TreeModel base class

### ISSUE THREAD

**Issue by jaap-karssenberg** [virtuald/pygi-treeview-dnd#4]
I'm trying to use the `PatchedTreeModel` in combination with model that overloads some of the TreeModel API. It looks like by inheriting from `PatchedTreeModel` my methods end up in the `Gtk.TreeModel` base rather than in my subclass where I define them. Really weird thing going on, best seen in the example attached.

The example is modified by defining a 2nd custom treemodel class which is not used at all. Just defining it modifies the behavior of the 1st treemodel class as well (here resulting in an error as I changed the model definition).

I'm at a loss how to debug further in this case...

**Comment by jaap-karssenberg** [comment]
Example of the issue here: https://gist.github.com/jaap-karssenberg/df6fcbd7dd565c333f66f4bdb00158e2

This is the default example from the repo with only one change which is the definition of `MyOtherModel`but without actually using it.

**Comment by virtuald** [comment]
Digging into this, not quite sure what's going on. However, not my bug -- if you just inherit from a Gtk.ListStore, the same problem occurs. Probably should file a bug against pygobject.

**Comment by jaap-karssenberg** [comment]
Stupid - I overlooked the difference between TreeStore and TreeModel. My original code derives from TreeModel not TreeStore and does not suffer from the issue.

Now trying to combine the patch metaclass directly while deriving from TreeModel + TreeDragSource . But this does not seem to work, getting back the error that no vfunc is found. Would there be any fundamental reason for this patch not working with the interface class ?

**Comment by jaap-karssenberg** [comment]
Created a new gist trying to use a TreeModel derived class. Demo is not functional but should run with empty tree. Instead it gives exception on loading the classes.

Fully appreciate it is not your bug, but any clue how to continue is welcome. Bit out of my knowledge zone when it comes to the C bindings here.

https://gist.github.com/jaap-karssenberg/b724cd232ef1c609e8b483ce90e132c8

**Comment by virtuald** [comment]
I'd recommend posting a bug on pygobject, as overriding a ListStore's virtual method shouldn't cause all ListStore objects to break -- so definitely something they would want to fix. If they can fix that, it'll probably fix your issue here.

Looking through this DnD code, the only thing I can remember is how annoying it was to put it together, and I'm a bit short on free time these days.

**Comment by jaap-karssenberg** [comment]
Yes, will open a bug for pygobject using an example without the patch.

Thanks for your time so far !

Regards,

Jaap
